$("#home").click(function (){
    $("#HomePage").css("display","block")
    $("#CarManagerPage").css("display","none")
    $("#AdminPage").css("display","none")
    $("#CustomersManagerPage").css("display","none")
    $("#PaymentPage").css("display","none")
    $("#DriversManagerPage").css("display","none")
    $("#ReservationsPage").css("display","none")
    $("#SchedulePage").css("display","none")
    $("#IncomePage").css("display","none")
});

$("#cars").click(function (){
    $("#HomePage").css("display","none")
    $("#CarManagerPage").css("display","block")
    $("#AdminPage").css("display","none")
    $("#CustomersManagerPage").css("display","none")
    $("#PaymentPage").css("display","none")
    $("#DriversManagerPage").css("display","none")
    $("#ReservationsPage").css("display","none")
    $("#SchedulePage").css("display","none")
    $("#IncomePage").css("display","none")
});

$("#admin").click(function (){
    $("#HomePage").css("display","none")
    $("#CarManagerPage").css("display","none")
    $("#AdminPage").css("display","block")
    $("#CustomersManagerPage").css("display","none")
    $("#PaymentPage").css("display","none")
    $("#DriversManagerPage").css("display","none")
    $("#ReservationsPage").css("display","none")
    $("#SchedulePage").css("display","none")
    $("#IncomePage").css("display","none")

})

$("#customers").click(function (){
    $("#HomePage").css("display","none")
    $("#CarManagerPage").css("display","none")
    $("#AdminPage").css("display","none")
    $("#CustomersManagerPage").css("display","block")
    $("#PaymentPage").css("display","none")
    $("#DriversManagerPage").css("display","none")
    $("#ReservationsPage").css("display","none")
    $("#SchedulePage").css("display","none")
    $("#IncomePage").css("display","none")
})

$("#payment").click(function (){
    $("#HomePage").css("display","none")
    $("#CarManagerPage").css("display","none")
    $("#AdminPage").css("display","none")
    $("#CustomersManagerPage").css("display","none")
    $("#PaymentPage").css("display","block")
    $("#DriversManagerPage").css("display","none")
    $("#ReservationsPage").css("display","none")
    $("#SchedulePage").css("display","none")
    $("#IncomePage").css("display","none")
})

$("#drivers").click(function (){
    $("#HomePage").css("display","none")
    $("#CarManagerPage").css("display","none")
    $("#AdminPage").css("display","none")
    $("#CustomersManagerPage").css("display","none")
    $("#PaymentPage").css("display","none")
    $("#DriversManagerPage").css("display","block")
    $("#ReservationsPage").css("display","none")
    $("#SchedulePage").css("display","none")
    $("#IncomePage").css("display","none")
})

$("#reservations").click(function (){
    $("#HomePage").css("display","none")
    $("#CarManagerPage").css("display","none")
    $("#AdminPage").css("display","none")
    $("#CustomersManagerPage").css("display","none")
    $("#PaymentPage").css("display","none")
    $("#DriversManagerPage").css("display","none")
    $("#ReservationsPage").css("display","block")
    $("#SchedulePage").css("display","none")
    $("#IncomePage").css("display","none")
})

$("#scheduleDetails").click(function (){
    $("#HomePage").css("display","none")
    $("#CarManagerPage").css("display","none")
    $("#AdminPage").css("display","none")
    $("#CustomersManagerPage").css("display","none")
    $("#PaymentPage").css("display","none")
    $("#DriversManagerPage").css("display","none")
    $("#ReservationsPage").css("display","none")
    $("#SchedulePage").css("display","block")
    $("#IncomePage").css("display","none")
})

$("#incomeDetails").click(function (){
    $("#HomePage").css("display","none")
    $("#CarManagerPage").css("display","none")
    $("#AdminPage").css("display","none")
    $("#CustomersManagerPage").css("display","none")
    $("#PaymentPage").css("display","none")
    $("#DriversManagerPage").css("display","none")
    $("#ReservationsPage").css("display","none")
    $("#SchedulePage").css("display","none")
    $("#IncomePage").css("display","block")
})